# Generated by Django 4.0.5 on 2022-06-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sementes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('preco', models.FloatField(max_length=100.2)),
            ],
        ),
    ]
