# Generated by Django 4.0.5 on 2022-06-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sementes', '0002_alter_sementes_descricao_alter_sementes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sementes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
