# Generated by Django 4.0.5 on 2022-06-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flores',
            name='id',
            field=models.IntegerField(primary_key=1, serialize=False),
        ),
        migrations.AlterField(
            model_name='flores',
            name='link',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='flores',
            name='preco',
            field=models.FloatField(max_length=100),
        ),
    ]
